### ISSUE TITLE
Load YamlConfiguration Error

### ISSUE THREAD

**Issue by segu23** [Carleslc/Simple-YAML#58]
When i do this: https://pastebin.com/ixXuxmEc

I have this error:

```
[11:47:27 INFO]: [PTC] Enabling PTC v1.0
[11:47:27 ERROR]: Error occurred while enabling PTC v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.<init>(Lorg/yaml/snakeyaml/constructor/BaseConstructor;Lorg/yaml/snakeyaml/representer/Representer;Lorg/yaml/snakeyaml/DumperOptions;Lorg/yaml/snakeyaml/LoaderOptions;Lorg/yaml/snakeyaml/resolver/Resolver;)V
        at org.simpleyaml.configuration.implementation.snakeyaml.SnakeYamlImplementation.setYaml(SnakeYamlImplementation.java:61) ~[?:?]
        at org.simpleyaml.configuration.implementation.snakeyaml.SnakeYamlImplementation.setYaml(SnakeYamlImplementation.java:48) ~[?:?]
        at org.simpleyaml.configuration.implementation.snakeyaml.SnakeYamlImplementation.<init>(SnakeYamlImplementation.java:44) ~[?:?]
        at org.simpleyaml.configuration.implementation.snakeyaml.SnakeYamlImplementation.<init>(SnakeYamlImplementation.java:40) ~[?:?]
        at org.simpleyaml.configuration.implementation.snakeyaml.SnakeYamlImplementation.<init>(SnakeYamlImplementation.java:36) ~[?:?]
        at org.simpleyaml.configuration.file.YamlConfiguration.<init>(YamlConfiguration.java:43) ~[?:?]
        at org.simpleyaml.configuration.file.YamlConfiguration.<init>(YamlConfiguration.java:33) ~[?:?]
        at org.kayteam.api.simple.yaml.SimpleYaml.reloadYamlFile(SimpleYaml.java:98) ~[?:?]
        at org.kayteam.api.simple.yaml.SimpleYaml.registerYamlFile(SimpleYaml.java:71) ~[?:?]
        at org.kayteam.ptc.PTC.registerFiles(PTC.java:51) ~[?:?]
        at org.kayteam.ptc.PTC.onEnable(PTC.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[11:47:27 INFO]: [PTC] Disabling PTC v1.0
```

**Comment by segu23** [comment]
Solved with
```
<relocations>
    <relocation>
        <pattern>org.simpleyaml</pattern>
        <shadedPattern>ir.ciph3r.eris.libs</shadedPattern>
    </relocation>
    <relocation>
        <pattern>org.yaml</pattern>
        <shadedPattern>ir.ciph3r.eris.libs</shadedPattern>
    </relocation>
</relocations>
```
and
```
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.30</version>
</dependency>
```
